name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - run: |
        env GOOS=linux GOARCH=amd64   go build -o bin/linux-amd64/k8s-create ./cmd/k8s-create
        env GOOS=linux GOARCH=amd64   go build -o bin/linux-amd64/k8s-list ./cmd/k8s-list
        env GOOS=linux GOARCH=amd64   go build -o bin/linux-amd64/storage-kafka ./cmd/storage-kafka
        env GOOS=linux GOARCH=amd64   go build -o bin/linux-amd64/storage-postgres ./cmd/storage-postgres

      - run: |
        env GOOS=darwin GOARCH=amd64  go build -o bin/mac-amd64/k8s-create ./cmd/k8s-create
        env GOOS=darwin GOARCH=amd64  go build -o bin/mac-amd64/k8s-list ./cmd/k8s-list
        env GOOS=darwin GOARCH=amd64  go build -o bin/mac-amd64/storage-kafka ./cmd/storage-kafka
        env GOOS=darwin GOARCH=amd64  go build -o bin/mac-amd64/storage-postgres ./cmd/storage-postgres

      - run: |
        env GOOS=windows GOARCH=amd64  go build -o bin/win-amd64/k8s-create ./cmd/k8s-create
        env GOOS=windows GOARCH=amd64  go build -o bin/win-amd64/k8s-list ./cmd/k8s-list
        env GOOS=windows GOARCH=amd64  go build -o bin/win-amd64/storage-kafka ./cmd/storage-kafka
        env GOOS=windows GOARCH=amd64  go build -o bin/win-amd64/storage-postgres ./cmd/storage-postgres

      - run: |
        zip toolbx-commands-linux-amd64.zip bin/linux-amd64/*
        zip toolbx-commands-mac-amd64.zip bin/mac-amd64/*
        zip toolbx-commands-win-amd64.zip bin/win-amd64/*
