name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - run: env GOOS=linux GOARCH=amd64 go build -o bin/linux-amd64/k8s-create ./cmd/k8s-create

